>all_greet_prog 100~
say DO NOT MULTI-PLAY.
say YOU MAY ONLY HAVE ONE CHARACTER ON AT A TIME.
say NONE OF YOUR CHARACTERS MAY HAVE KNOWLEDGE OF ANY OF YOUR OTHER CHARACTERS.
say FAILURE TO FOLLOW THESE RULES WILL RESULT IN SEVER PENALTIES.
say IT IS QUITE EASY FOR THE IMMORTALS TO CATCH YOU.
~
|

